### ISSUE TITLE
Getting access denied with partially modified files

### ISSUE THREAD

**Issue by tfwoodland** [UnrealisticDev/Renom#8] opened 2023-01-12 06:18 UTC
So not sure how to approach this, no matter what I do, whether I put in new name for each detected module and file I always end up with access denied prompt at the end and an prompt to revert the changes.

**Comment by tfwoodland** [comment] 2023-01-12 10:25
Moving folder to C:/ seems like a interim solution. However, even though it ends the process, code does not compile, not the project runs. I'm on 5.1 so are there any requirements to make it work, or any additional steps to take ? Or the program doesn't support 5.1 ?

**Comment by msmoiz** [comment] 2023-01-13 00:28
Can you provide a link to a minimal project that reproduces this issue? Output logs for the failed runs would help as well.

**Comment by VirtualLilies** [comment] 2023-01-24 10:47
> Can you provide a link to a minimal project that reproduces this issue? Output logs for the failed runs would help as well.

All I can say is that it is multi module cpp project, based on CitySample with my custom module running on 5.1. I think you can test it out with running Renom with CitySample from Epic. The reason to rename is to have the exe named after the project, which in case of basing the project on CitySample, the *.exe always gets named CitySample.exe. I haven't tried to rename manually since there are way to many classes and simply not worth it, at least for the time being. Also sorry to post from different account ;)

**Comment by msmoiz** [comment] 2023-03-10 21:32
Without more information (logs, error messages, reproducible project), there is not much that can be done. Closing for now. Please reopen if you are able to provide additional information.

**Closed by msmoiz** 2023-03-10 21:32 UTC

**Comment by VirtualLilies** [comment] 2023-03-10 21:34
As an example download city sample add your own module and try to run the renamer.

**Comment by msmoiz** [comment] 2023-03-18 07:43
What is the error message that you are seeing? Are you sure that you are not running the program from within the folder that the project or module is contained in? That can cause permission issues.

**Comment by VirtualLilies** [comment] 2023-03-21 22:36
Managed to successfully rename modules, however I did have to manually fix some includes not updating. Either way I can consider this solved. I assume that running .exe from desktop solved the issue since I was trying to run renom from cmd from within the project folder.
